version: '3.8'

services:
  payments-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=post@123
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - globalbooks-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=globalbooks_payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - globalbooks-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - globalbooks-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  globalbooks-network:
    driver: bridge